//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ogani.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chapter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public chapter()
        {
            this.comments = new HashSet<comment>();
        }
    
        public int chapter_id { get; set; }
        public int novel_id { get; set; }
        public int chapter_number { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<bool> is_available { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
        public virtual novel novel { get; set; }
    }
}
