//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ogani.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_read_novels
    {
        public int user_id { get; set; }
        public int novel_id { get; set; }
        public Nullable<int> last_read_chapter_id { get; set; }
    
        public virtual novel novel { get; set; }
        public virtual user user { get; set; }
    }
}
